### ISSUE TITLE
Better errors + cleanup when `renga init` is executed in an already existing git repo

### ISSUE THREAD

**Issue by spMohanty** [SwissDataScienceCenter/renga-python#136]
If you run `renga init` in an already existing git repo, the error is confusing, and hard to know about the `-f` flag.
Also, it does not rollback or cleanup the `.renga` folder it created in the process, which throws error when you try a `renga init -f` later.

If you run `renga init` in an already existing `renga repo`, the error is confusing as you get a `FileExistsError`.

**Comment by rokroskar** [comment]
closed via #141, continued by #142
