### ISSUE TITLE
implement repr or str on models

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renga-python#37]
Now: `<renga.models.deployer.Context at 0x7f54d419eb00>`
Expected: `Context(id=foobar, ...)` on all models

**Comment by jirikuncar** [comment]
all models have `__str__` by now

**Comment by rokroskar** [comment]
the current implementation gives:

```
client.contexts.list()
[<Context 'bc5c6d4e-ad14-4cbb-9917-918ba99ffe3e'>,
 <Context 'a1beb2f1-f749-44a5-a854-d8635345f79b'>]
```

or e.g. 

```
client.buckets.list()
[<Bucket '8216'>]
```

closing this for now
