### ISSUE TITLE
possibility to upload/download files from CLI

### ISSUE THREAD

**Issue by ebiiii** [SwissDataScienceCenter/renga-python#62]
like for example (it can be different): 

`renga io buckets upload BUCKET_ID FILENAME`

`renga io download FILE_ID  > FILENAME`

**Comment by jirikuncar** [comment]
> `renga io buckets upload BUCKET_ID FILENAME`

see `renga add`

**Comment by leafty** [comment]
`renga add` is coarse grained, and requires to have a default bucket setup in the project. I'd see benefits in having fine-grained control over file, versions, etc.

**Comment by rokroskar** [comment]
I guess that behavior can easily be changed/amended with commandline options

**Comment by leafty** [comment]
Also, `add` was not mentioned in the docs (https://renga.readthedocs.io/en/latest/user/firststeps.html#creating-and-populating-a-storage-bucket). I guess that's why @ebiiii created the issue.

**Comment by rokroskar** [comment]
true, this has not percolated down to the docs yet. I've created an issue

**Comment by jirikuncar** [comment]
FYI there is:

```console
$ renga --help
```
