### ISSUE TITLE
`default_bucket` used in `add` when `autosync=true` but it is not defined at `init` time

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renga-python#64]
In other words, the default bucket is not created by the cli at project creation time

**Comment by leafty** [comment]
Edit: did not see https://github.com/SwissDataScienceCenter/renga-python/blob/master/renga/cli/io.py#L59-L66.
But is it desired to change the default bucket every time one is created?

**Comment by jirikuncar** [comment]
> But is it desired to change the default bucket every time one is created?

It's not changing it every time - see https://github.com/SwissDataScienceCenter/renga-python/blob/master/renga/cli/io.py#L65-L66 and https://docs.python.org/3/library/stdtypes.html#dict.setdefault
